ruby-pipeline:
  source:
    log_generator:
      log_type:
        vpc_flow:
  processor:
    - csv:
        column_names: ["VPC_FLOW_LOGS_VERSION", "AccountId", "InterfaceId", "SourceIp", "DestinationIp", "SourcePort", "DestinationPort", "Packets", "Bytes", "StartTime", "EndTime", "Action", "LogStatus"]
        delimiter: " "
    - ruby:
        code: "event.put('flow_duration_in_seconds', 0.001 * (event.get('EndTime').to_i - event.get('StartTime').to_i))"
  route:
    - long_flow_duration: '/flow_duration_in_seconds > 0.7'
  sink:
    - stdout:
    - opensearch:
        hosts:
          - "https://opensearch:9200"
        insecure: true
        username: "admin"
        password: "admin"
        index: flow_logs
    - opensearch:
        routes:
          -  long_flow_duration
        hosts:
          - "https://opensearch:9200"
        insecure: true
        username: "admin"
        password: "admin"
        index: slow_flow_logs